Part 3 >>>OPERATIONAL
>>>MODIFICATIONS
--STUB method getColorString

>>>DEFICITS
--Line 23, incompatible types: java.lang.String[] cannot be converted to java.util.List<java.lang.String>

>>>BUGS
--C:\Users\Gnomatic\IdeaProjects\Java-Assignment-010\src\Dog.java
  Warning:(1, 1) Unused import statement
  Warning:(8, 20) Private field 'name' is assigned but never accessed
  Warning:(8, 20) Field can be converted to a local variable
  Warning:(8, 20) Field 'name' may be 'final'
  Warning:(9, 20) Private field 'breed' is assigned but never accessed
  Warning:(9, 20) Field can be converted to a local variable
  Warning:(9, 20) Field 'breed' may be 'final'
  Warning:(10, 22) Private field 'color' is assigned but never accessed
  Warning:(10, 22) Field can be converted to a local variable
  Warning:(10, 22) Field 'color' may be 'final'
  Warning:(11, 17) Private field 'age' is assigned but never accessed
  Warning:(11, 17) Field can be converted to a local variable
  Warning:(11, 17) Field 'age' may be 'final'
  Warning:(12, 27) Field can be converted to a local variable
  Warning:(12, 27) Field 'printTemplate' may be 'final'
  Error:(23, 74) 'getColorString(java.util.List<java.lang.String>)' in 'Dog' cannot be applied to '(java.lang.String[])'
  Warning:(25, 9) 'return' is unnecessary as the last statement in a constructor
  Warning:(78, 17) Condition 'i < colorSize' is always 'true'
  Warning:(87, 17) Method 'eat()' is never used
  Warning:(88, 9) 'return' is unnecessary as the last statement in a 'void' method
  Warning:(90, 17) Method 'run()' is never used
  Warning:(91, 9) 'return' is unnecessary as the last statement in a 'void' method
  Warning:(93, 17) Method 'sleep()' is never used
  Warning:(94, 9) 'return' is unnecessary as the last statement in a 'void' method
  Warning:(96, 17) Method 'name()' is never used
  Warning:(97, 9) 'return' is unnecessary as the last statement in a 'void' method
  Warning:(103, 13) Variable 'dog1' is never used
  Warning:(105, 13) Variable 'dog2' is never used
  Warning:(107, 13) Variable 'dog3' is never used
  Warning:(108, 9) 'return' is unnecessary as the last statement in a 'void' method